In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer

In [3]:
data=load_breast_cancer()

In [4]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], shape=(569, 30))

In [5]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [6]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [7]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [8]:
df=pd.DataFrame(np.c_[data.data,data.target],columns=[list(data.feature_names)+['target']])
df

mean radius mean texture mean perimeter mean area mean smoothness  \
0         17.99        10.38         122.80    1001.0         0.11840   
1         20.57        17.77         132.90    1326.0         0.08474   
2         19.69        21.25         130.00    1203.0         0.10960   
3         11.42        20.38          77.58     386.1         0.14250   
4         20.29        14.34         135.10    1297.0         0.10030   
..          ...          ...            ...       ...             ...   
564       21.56        22.39         142.00    1479.0         0.11100   
565       20.13        28.25         131.20    1261.0         0.09780   
566       16.60        28.08         108.30     858.1         0.08455   
567       20.60        29.33         140.10    1265.0         0.11780   
568        7.76        24.54          47.92     181.0         0.05263   

    mean compactness mean concavity mean concave points mean symmetry  \
0            0.27760        0.30010             0.14710        0.2419   
1            0.07864        0.08690             0.07017        0.1812   
2            0.15990        0.19740             0.12790        0.2069   
3            0.28390        0.24140             0.10520        0.2597   
4            0.13280        0.19800             0.10430        0.1809   
..               ...            ...                 ...           ...   
564          0.11590        0.24390             0.13890        0.1726   
565          0.10340        0.14400             0.09791        0.1752   
566          0.10230        0.09251             0.05302        0.1590   
567          0.27700        0.35140             0.15200        0.2397   
568          0.04362        0.00000             0.00000        0.1587   

    mean fractal dimension  ... worst texture worst perimeter worst area  \
0                  0.07871  ...         17.33          184.60     2019.0   
1                  0.05667  ...         23.41          158.80     1956.0   
2                  0.05999  ...         25.53          152.50     1709.0   
3                  0.09744  ...         26.50           98.87      567.7   
4                  0.05883  ...         16.67          152.20     1575.0   
..                     ...  ...           ...             ...        ...   
564                0.05623  ...         26.40          166.10     2027.0   
565                0.05533  ...         38.25          155.00     1731.0   
566                0.05648  ...         34.12          126.70     1124.0   
567                0.07016  ...         39.42          184.60     1821.0   
568                0.05884  ...         30.37           59.16      268.6   

    worst smoothness worst compactness worst concavity worst concave points  \
0            0.16220           0.66560          0.7119               0.2654   
1            0.12380           0.18660          0.2416               0.1860   
2            0.14440           0.42450          0.4504               0.2430   
3            0.20980           0.86630          0.6869               0.2575   
4            0.13740           0.20500          0.4000               0.1625   
..               ...               ...             ...                  ...   
564          0.14100           0.21130          0.4107               0.2216   
565          0.11660           0.19220          0.3215               0.1628   
566          0.11390           0.30940          0.3403               0.1418   
567          0.16500           0.86810          0.9387               0.2650   
568          0.08996           0.06444          0.0000               0.0000   

    worst symmetry worst fractal dimension target  
0           0.4601                 0.11890    0.0  
1           0.2750                 0.08902    0.0  
2           0.3613                 0.08758    0.0  
3           0.6638                 0.17300    0.0  
4           0.2364                 0.07678    0.0  
..             ...                     ...    ...  
564         0.2060      

In [9]:
df.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760         0.3001             0.14710        0.2419   
1          0.07864         0.0869             0.07017        0.1812   
2          0.15990         0.1974             0.12790        0.2069   
3          0.28390         0.2414             0.10520        0.2597   
4          0.13280         0.1980             0.10430        0.1809   

  mean fractal dimension  ... worst texture worst perimeter worst area  \
0                0.07871  ...         17.33          184.60     2019.0   
1                0.05667  ...         23.41          158.80     1956.0   
2                0.05999  ...         25.53          152.50     1709.0   
3                0.09744  ...         26.50           98.87      567.7   
4                0.05883  ...         16.67          152.20     1575.0   

  worst smoothness worst compactness worst concavity worst concave points  \
0           0.1622            0.6656          0.7119               0.2654   
1           0.1238            0.1866          0.2416               0.1860   
2           0.1444            0.4245          0.4504               0.2430   
3           0.2098            0.8663          0.6869               0.2575   
4           0.1374            0.2050          0.4000               0.1625   

  worst symmetry worst fractal dimension target  
0         0.4601                 0.11890    0.0  
1         0.2750                 0.08902    0.0  
2         0.3613                 0.08758    0.0  
3         0.6638                 0.17300    0.0  
4         0.2364                 0.07678    0.0  

[5 rows x 31 columns]

In [10]:
df.tail()

mean radius mean texture mean perimeter mean area mean smoothness  \
564       21.56        22.39         142.00    1479.0         0.11100   
565       20.13        28.25         131.20    1261.0         0.09780   
566       16.60        28.08         108.30     858.1         0.08455   
567       20.60        29.33         140.10    1265.0         0.11780   
568        7.76        24.54          47.92     181.0         0.05263   

    mean compactness mean concavity mean concave points mean symmetry  \
564          0.11590        0.24390             0.13890        0.1726   
565          0.10340        0.14400             0.09791        0.1752   
566          0.10230        0.09251             0.05302        0.1590   
567          0.27700        0.35140             0.15200        0.2397   
568          0.04362        0.00000             0.00000        0.1587   

    mean fractal dimension  ... worst texture worst perimeter worst area  \
564                0.05623  ...         26.40          166.10     2027.0   
565                0.05533  ...         38.25          155.00     1731.0   
566                0.05648  ...         34.12          126.70     1124.0   
567                0.07016  ...         39.42          184.60     1821.0   
568                0.05884  ...         30.37           59.16      268.6   

    worst smoothness worst compactness worst concavity worst concave points  \
564          0.14100           0.21130          0.4107               0.2216   
565          0.11660           0.19220          0.3215               0.1628   
566          0.11390           0.30940          0.3403               0.1418   
567          0.16500           0.86810          0.9387               0.2650   
568          0.08996           0.06444          0.0000               0.0000   

    worst symmetry worst fractal dimension target  
564         0.2060                 0.07115    0.0  
565         0.2572                 0.06637    0.0  
566         0.2218                 0.07820    0.0  
567         0.4087                 0.12400    0.0  
568         0.2871                 0.07039    1.0  

[5 rows x 31 columns]

In [11]:
df.shape

(569, 31)

In [12]:
#Split_Data

In [13]:
x=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2020)
print("shape of x_train=",x_train.shape)
print("shape of x_test=",x_test.shape)
print("shape of y_train=",y_train.shape)
print("shape of y_test=",y_test.shape)

shape of x_train= (455, 30)
shape of x_test= (114, 30)
shape of y_train= (455,)
shape of y_test= (114,)


In [15]:
#Train K_Nearest Classification Model

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
classifier=KNeighborsClassifier(n_neighbors=5)

In [18]:
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [19]:
classifier.score(x_test,y_test)

0.9298245614035088

In [20]:
# Predict cancer

In [21]:
pt=[17.990,10.38,122.80,1001.0,0.11840,0.27760,0.300100,0.147100,0.2419,0.07871,1.0950,0.9053,8.5890,153.400,0.006399,0.049040,0.053730,0.015870,0.030030,0.006193,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.711900,0.265400,0.4601,0.11890]

In [22]:
pt

[17.99,
 10.38,
 122.8,
 1001.0,
 0.1184,
 0.2776,
 0.3001,
 0.1471,
 0.2419,
 0.07871,
 1.095,
 0.9053,
 8.589,
 153.4,
 0.006399,
 0.04904,
 0.05373,
 0.01587,
 0.03003,
 0.006193,
 25.38,
 17.33,
 184.6,
 2019.0,
 0.1622,
 0.6656,
 0.7119,
 0.2654,
 0.4601,
 0.1189]

In [23]:
pt1=np.array([pt])
pt1

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]])

In [24]:
classifier.predict(pt1)

array([0.])

In [25]:
classifier.predict(x_test)

array([0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
       0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0.,
       1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1.,
       0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1.])

In [26]:
pred=classifier.predict(pt1)

if pred[0]==0:
    print("patient has no cancer")
else:
    print("patient has cancer")

patient has no cancer


In [27]:
import pandas as pd
from sklearn.datasets import load_iris
data=load_iris()


In [28]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [29]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [30]:
df=pd.DataFrame(data.data,columns=data.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [31]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
df=pd.DataFrame(np.c_[data.data,data.target],columns=[list(data.feature_names)+['target']])
df

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm)  \
0                 5.1              3.5               1.4              0.2   
1                 4.9              3.0               1.4              0.2   
2                 4.7              3.2               1.3              0.2   
3                 4.6              3.1               1.5              0.2   
4                 5.0              3.6               1.4              0.2   
..                ...              ...               ...              ...   
145               6.7              3.0               5.2              2.3   
146               6.3              2.5               5.0              1.9   
147               6.5              3.0               5.2              2.0   
148               6.2              3.4               5.4              2.3   
149               5.9              3.0               5.1              1.8   

    target  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0  
..     ...  
145    2.0  
146    2.0  
147    2.0  
148    2.0  
149    2.0  

[150 rows x 5 columns]

In [33]:
x=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2020)
print("shape of x_train=",x_train.shape)
print("shape of x_test=",x_test.shape)
print("shape of y_train=",y_train.shape)
print("shape of y_test=",y_test.shape)

shape of x_train= (120, 4)
shape of x_test= (30, 4)
shape of y_train= (120,)
shape of y_test= (30,)


In [35]:
from sklearn.neighbors import KNeighborsClassifier

In [36]:
classifier=KNeighborsClassifier(n_neighbors=5)

In [37]:
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [38]:
pt=[5.1,3.5,1.4,0.2]

In [39]:
pt1=np.array([pt])

In [40]:
classifier.predict(pt1)

array([0.])

In [41]:
data=pd.read_csv(r"https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/taxis.csv")
data

pickup              dropoff  passengers  distance  fare  \
0     2019-03-23 20:21:09  2019-03-23 20:27:24           1      1.60   7.0   
1     2019-03-04 16:11:55  2019-03-04 16:19:00           1      0.79   5.0   
2     2019-03-27 17:53:01  2019-03-27 18:00:25           1      1.37   7.5   
3     2019-03-10 01:23:59  2019-03-10 01:49:51           1      7.70  27.0   
4     2019-03-30 13:27:42  2019-03-30 13:37:14           3      2.16   9.0   
...                   ...                  ...         ...       ...   ...   
6428  2019-03-31 09:51:53  2019-03-31 09:55:27           1      0.75   4.5   
6429  2019-03-31 17:38:00  2019-03-31 18:34:23           1     18.74  58.0   
6430  2019-03-23 22:55:18  2019-03-23 23:14:25           1      4.14  16.0   
6431  2019-03-04 10:09:25  2019-03-04 10:14:29           1      1.12   6.0   
6432  2019-03-13 19:31:22  2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment            pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card        Lenox Hill West   
1     0.00    0.0   9.30  yellow         cash  Upper West Side South   
2     2.36    0.0  14.16  yellow  credit card          Alphabet City   
3     6.15    0.0  36.95  yellow  credit card              Hudson Sq   
4     1.10    0.0  13.40  yellow  credit card           Midtown East   
...    ...    ...    ...     ...          ...                    ...   
6428  1.06    0.0   6.36   green  credit card      East Harlem North   
6429  0.00    0.0  58.80   green  credit card                Jamaica   
6430  0.00    0.0  17.30   green         cash    Crown Heights North   
6431  0.00    0.0   6.80   green  credit card          East New York   
6432  3.36    0.0  20.16   green  credit card            Boerum Hill   

                          dropoff_zone pickup_borough dropoff_borough  
0                  UN/Turtle Bay South      Manhattan       Manhattan  
1                Upper West Side South      Manhattan       Manhattan  
2                         West Village      Manhattan       Manhattan  
3                       Yorkville West      Manhattan       Manhattan  
4                       Yorkville West      Manhattan       Manhattan  
...                                ...            ...             ...  
6428              Central Harlem North      Manhattan       Manhattan  
6429  East Concourse/Concourse Village         Queens           Bronx  
6430                    Bushwick North       Brooklyn        Brooklyn  
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn  
6432                   Windsor Terrace       Brooklyn        Brooklyn  

[6433 rows x 14 columns]

In [42]:
import numpy as np
import pandas as pd

In [43]:
from sklearn.datasets import load_wine
data=load_wine()
data


{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]], shape=(178, 13)),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [44]:
data.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [45]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [46]:
data.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [47]:
df=pd.DataFrame(np.c_[data.data,data.target],columns=[list(data.feature_names)+['target']])
df

alcohol malic_acid   ash alcalinity_of_ash magnesium total_phenols  \
0     14.23       1.71  2.43              15.6     127.0          2.80   
1     13.20       1.78  2.14              11.2     100.0          2.65   
2     13.16       2.36  2.67              18.6     101.0          2.80   
3     14.37       1.95  2.50              16.8     113.0          3.85   
4     13.24       2.59  2.87              21.0     118.0          2.80   
..      ...        ...   ...               ...       ...           ...   
173   13.71       5.65  2.45              20.5      95.0          1.68   
174   13.40       3.91  2.48              23.0     102.0          1.80   
175   13.27       4.28  2.26              20.0     120.0          1.59   
176   13.17       2.59  2.37              20.0     120.0          1.65   
177   14.13       4.10  2.74              24.5      96.0          2.05   

    flavanoids nonflavanoid_phenols proanthocyanins color_intensity   hue  \
0         3.06                 0.28            2.29            5.64  1.04   
1         2.76                 0.26            1.28            4.38  1.05   
2         3.24                 0.30            2.81            5.68  1.03   
3         3.49                 0.24            2.18            7.80  0.86   
4         2.69                 0.39            1.82            4.32  1.04   
..         ...                  ...             ...             ...   ...   
173       0.61                 0.52            1.06            7.70  0.64   
174       0.75                 0.43            1.41            7.30  0.70   
175       0.69                 0.43            1.35           10.20  0.59   
176       0.68                 0.53            1.46            9.30  0.60   
177       0.76                 0.56            1.35            9.20  0.61   

    od280/od315_of_diluted_wines proline target  
0                           3.92  1065.0    0.0  
1                           3.40  1050.0    0.0  
2                           3.17  1185.0    0.0  
3                           3.45  1480.0    0.0  
4                           2.93   735.0    0.0  
..                           ...     ...    ...  
173                         1.74   740.0    2.0  
174                         1.56   750.0    2.0  
175                         1.56   835.0    2.0  
176                         1.62   840.0    2.0  
177                         1.60   560.0    2.0  

[178 rows x 14 columns]

In [48]:
x=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [49]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)
print("shape of x_train=",x_train.shape)
print("shape of x_test=",x_test.shape)
print("shape of y_train=",y_train.shape)
print("shape of y_test=",y_test.shape)

shape of x_train= (142, 13)
shape of x_test= (36, 13)
shape of y_train= (142,)
shape of y_test= (36,)


In [50]:
from sklearn.neighbors import KNeighborsClassifier

In [51]:
classifier=KNeighborsClassifier(n_neighbors=7)

In [52]:
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [53]:
pt=[14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0]

In [54]:
pt1=np.array([pt])

In [55]:
classifier.predict(pt1)

array([0.])

In [21]:
data=pd.read_csv(r"https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/planets.csv")
data

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [22]:
data.columns

Index(['method', 'number', 'orbital_period', 'mass', 'distance', 'year'], dtype='object')

In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [25]:
import seaborn as sns
data = sns.load_dataset("planets")
data.head()


method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [26]:
data.isnull().sum()


method              0
number              0
orbital_period     43
mass              522
distance          227
year                0
dtype: int64

In [27]:
data = data.dropna()


In [28]:
X = data[['number', 'orbital_period', 'mass', 'distance', 'year']]  # numerical columns
y = data['method']  # target


In [29]:
le = LabelEncoder()
y = le.fit_transform(y)


In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [31]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [32]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)


KNeighborsClassifier()

In [33]:
y_pred = knn.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 1.0

Confusion Matrix:
 [[100]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       100

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:534: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(
